config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  # /スラッシュにアクセスした時toppages#indexに飛ぶルーティング
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create]
  
  resources :items, only: [:show, :new]
  resources :ownerships, only: [:create, :destroy]
  # (new)楽天APIを使った検索結果を表示するページ///検索したもの全てを保存する必要はない
  # (show)共有したいものだけを保存する///Want,Have機能の実装時にItemを保存する
  # resources :ownerships, only: [:create, :destroy]
  # ownerships///中間テーブル
  
  get 'rankings/want', to: 'rankings#want'
  get 'rankings/have', to: 'rankings#have'
end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
# ItemのWantボタンが押されたらこのアクションに行き着く。このタイミングでItemを保存する
  def create
    @item = Item.find_or_initialize_by(code: params[:item_code])
      # 探してみつかれば,保存されていたインスタンスを返す///みつからなければItem.new新規作成
      # wantボタンは１つのアイテムに対して行うアクションである なので、単数形
    
    unless @item.persisted?
        # @item.persisted?///取得したインスタンス@itemすでに保存されているか判断する
        # unless @item.persisted?///保存されていなければtrue ＝ ブロック内の処理を実行(保存する)
        # @item が保存されていない場合、先に @item を保存する
        # ///persisted 残存する
      results = RakutenWebService::Ichiba::Item.search(itemCode: @item.code)
        # itemCode(楽天市場商品のid)で楽天市場を検索する///要素１つの配列として返ってくるので
        # result.firstで唯一の要素を取得
        # readはあとでapplication_controller.rbへ移動する前提で使用している
        # items_controller.rb/read(result.first)のreadはそのままだと使えないため
      @item = Item.new(read(results.first))
      @item.save
    end
    
    # Want 関係として保存
    if params[:type] == 'Want'
        # HAVE と区別するため
        # params[:type]はフォームを作成するときに設定する
      current_user.want(@item)
        # current_user///helperで定義
        # wantメソッドは @item.id を必要とする。なければスルーしてしまう
        # unless @item.persisted? のブロックで保存は完了している
      flash[:success] = '商品を Want しました。'
    elsif params[:type] =='Have'
      current_user.have(@item)
      flash[:success] = '商品を Have しました。'
    end
    
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @item = Item.find(params[:item_id])
    
    if params[:type] == 'Want'
      current_user.unwant(@item)
      flash[:success] = '商品の Want を解除しました。'
    elsif params[:type] =='Have'
      current_user.unhave(@item)
      flash[:success] = '商品の Have を解除しました。'
    end
    
    redirect_back(fallback_location: root_path)
  end
end

app/views/ownerships/_have_button.html.erb
<% if current_user.have?(item) %>
  <%= form_tag(ownership_path(item.id), method: :delete) do %>
    <%= hidden_field_tag :item_id, item.id %>
    <%= hidden_field_tag :type, 'Have' %>
    <%= submit_tag 'Have', class: 'btn btn-success' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :item_code, item.code %>
    <%= hidden_field_tag :type, 'Have' %>
    <%= submit_tag 'Have it', class:'btn btn-primary' %>
  <% end %>
<% end %>

<!--typeも渡す-->
<!--ownership_controllerでも使用されているので要確認-->

app/views/ownerships/_want_button.html.erb
<% if current_user.want?(item) %>
  <%= form_tag(ownership_path(item.id), method: :delete) do %>
    <%= hidden_field_tag :item_id, item.id %>
    <%= hidden_field_tag :type, 'Want' %>
    <%= submit_tag 'Want', class: 'btn btn-success' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :item_code, item.code %>
    <%= hidden_field_tag :type, 'Want' %>
    <%= submit_tag 'Want it', class:'btn btn-primary' %>
  <% end %>
<% end %>

<!--wantしているか否かでボタンをだし分ける-->
<!--すでにwantしていて、それをdestroyする場合　保存されていた item_id があるのでそれをを渡す-->
<!--未wantで新しくwantする場合、item_id がないので item_code を渡す-->
<!--typeも渡す-->
<!--ownership_controllerでも使用されているので要確認-->